version: '2'

services:

# SPARK ----------------------------------------------------------------------------------------------------------------

    spark:
        image: docker.io/bitnami/spark:3
        container_name: spark-master
        restart: always
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - '8080:8080' # Web ui port
            - '7077:7077'
            - '4040:4040'
        volumes:
            - ./target:/opt/bitnami/spark/queries/

    spark-worker:
        image: docker.io/bitnami/spark:3
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=2g
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        depends_on:
            -   spark

# HDFS -----------------------------------------------------------------------------------------------------------------

    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        container_name: namenode
        restart: always
        environment:
            - CLUSTER_NAME=test
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - HDFS_CONF_dfs_permissions_enabled=false
            - HDFS_CONF_dfs_replication=1
        ports:
            - '9870:9870'
            - '9000:9000'

    datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        depends_on:
            -   namenode

# NIFI -----------------------------------------------------------------------------------------------------------------

    nifi:
        image: apache/nifi
        container_name: nifi
        ports:
            - '9090:8080' # Web ui port
        volumes:
            - ./nifi:/nifi_config/
            - nifi_volume:/opt/nifi/nifi-current/conf/

# REDIS ----------------------------------------------------------------------------------------------------------------

    redis:
        image: docker.io/bitnami/redis:6.2
        container_name: redis
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/bitnami/redis/data

volumes:
    redis_data:
    nifi_volume: