version: '2'

services:

# SPARK ----------------------------------------------------------------------------------------------------------------

    spark:
        image: docker.io/bitnami/spark:3
        container_name: spark-master
        restart: always
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        ports:
            - '8080:8080' # Web ui port
            - '7077:7077'
        volumes:
            - ./target:/opt/bitnami/spark/queries/

    spark-worker:
        image: docker.io/bitnami/spark:3
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1g
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        depends_on:
            -   spark

# HDFS -----------------------------------------------------------------------------------------------------------------

    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        container_name: namenode
        restart: always
        environment:
            - CLUSTER_NAME=test
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
            - HDFS_CONF_dfs_permissions_enabled=false
            - HDFS_CONF_dfs_replication=1
        ports:
            - '9870:9870'
            - '9000:9000'
        #volumes:
            #- hadoop_namenode:/hadoop/dfs/name

    datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        depends_on:
            -   namenode
        #volumes:
            #- hadoop_datanode:/hadoop/dfs/data

# NIFI -----------------------------------------------------------------------------------------------------------------

    nifi:
        image: apache/nifi
        container_name: nifi
        ports:
            - '9090:8080' # Web ui port
        volumes:
            - ./nifi:/nifi_config/
            - nifi_volume:/opt/nifi/nifi-current/conf/

# REDIS ----------------------------------------------------------------------------------------------------------------

    redis-master:
        image: bitnami/redis:latest
        ports:
            - '6379:6379'
        environment:
            - REDIS_REPLICATION_MODE=master
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - redis_volume:/bitnami

    redis-replica:
        image: bitnami/redis:latest
        ports:
            - '6379'
        depends_on:
            - redis-master
        environment:
            - REDIS_REPLICATION_MODE=slave
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6379
            - ALLOW_EMPTY_PASSWORD=yes

# GRAFANA --------------------------------------------------------------------------------------------------------------

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        environment:
            - GF_INSTALL_PLUGINS=redis-datasource
        ports:
            - '3000:3000'
        user: "104"

#-----------------------------------------------------------------------------------------------------------------------

volumes:
    redis_volume:
    nifi_volume:
    hadoop_namenode:
    hadoop_datanode: